var FLAG_INITIALIZED = 1;
var FLAG_UPDATE = 2;
var FLAG_HAS_DRAG = 4;
var FLAG_DRAG_CONTAINER = 8;
var FLAG_CONTAINER = 16;
var FLAG_DRAG_CONT_CALCULATED = 32;
var FLAG_CONTENT_INJESTED = 64;

var STATE_TEXT = 0;
var STATE_PRE_KEY = 1;
var STATE_KEY = 2;

var QUERY_SELF = 1;
var QUERY_PARENTS = 2;
var QUERY_CHILDREN = 4;

var EVENT_QUERY = 16;
var ELEM_QUERY = 17;
